name: Run RestAssured API Tests

on:
  push:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Specify your Java version
          distribution: 'temurin'

      # Step 3: Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
     
      # Step 4: Install Allure Command-Line Tool
      - name: Install Allure
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/latest/download/allure-commandline.zip
          powershell -Command "Expand-Archive -Path allure.zip -DestinationPath allure-cli"
          setx PATH "%cd%\\allure-cli\\bin;%PATH%"
        shell: cmd

      # Step 5: Verify Allure Installation
      - name: Verify Allure Installation
        run: allure --version

      # Step 6: Run Maven Tests
      - name: Run Tests
        run: mvn clean test

      # Step 7: Generate Allure Report
      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report

      # Step 8: Upload Allure Report as Artifact (Optional)
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report
