name: Run RestAssured API Tests

on:
  push:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Specify your Java version
          distribution: 'temurin'

      # Step 3: Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 4: Run Maven clean test
      - name: Run tests
        run: mvn clean test

      # Step 5: Run Allure Report
      - name: Run Allure Report
        run: allure serve allure-results
